# Site settings
title: "Jekyll Boilerplate"
description: "site description goes here"

url: http://yourdomain.com
headshot: http://96aa48.github.io/face.png
portfoliobackground: http://static.simpledesktops.com/uploads/desktops/2014/07/09/Satellites-Wallpaper.png
permalink: date

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
